### ISSUE TITLE
Duplicate values in results dashboard

### ISSUE THREAD

**Issue by jonasVano** [open-modex/result_comparison#1]
@henhuy : Please check:

I always get duplicate values in the dashboard. I think this is because of the values, that have a list of regions. Those cannot be filtered correctly.

**Comment by henhuy** [comment]
Already added "Show data" to show data table of current filter settings.
Could you check underlying data and see why there are duplicates?

Will move quotation issue to own issue...

**Comment by henhuy** [comment]
Fixed - regions are not unpacked
