### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by LKoeckritz** [open-modex/result_comparison#3]
I've again tried uploading our data (ID30, 2016) and receive an internal server error again. I think I eliminated the bugs from last time and cannot see what goes wrong now due to the server error. 

It would be very helpful to know what I am doing wrong this time :) @henhuy 

Our datapackage: [MODEX_ID30_2016.zip](https://github.com/open-modex/result_comparison/files/6392672/MODEX_ID30_2016.zip)

**Comment by henhuy** [comment]
Hi Luja,

es fehlte ein Komma in der datapackage.json, Zeile 48 :(
(da muss ich noch eine sinnvolle Fehlermeldung ausgeben...)
Habe das Komma eingefügt und hochgeladen - hat jetzt die ID 31
