### ISSUE TITLE
Data not always properly shown

### ISSUE THREAD

**Issue by jonasVano** [open-modex/result_comparison#6]
Sometimes, there is data shown in the graph but there is no data when I click show data:

![image](https://user-images.githubusercontent.com/56714321/116994050-8b01da80-acd8-11eb-9621-b7330a69e473.png)

Any ideas?

**Comment by jonasVano** [comment]
Also it is not showing any data for GENESYS-MOD ... although there is data !

**Comment by henhuy** [comment]
Could you check again?
I can see data!
(And genesys-mod rows are present, but values to small to be shown)

**Comment by henhuy** [comment]
This is due to too long response times - should be improved in new version.
Please reopen issue, if this happens again...
