### ISSUE TITLE
Multiple equal values

### ISSUE THREAD

**Issue by jonasVano** [open-modex/result_comparison#7]
The dashboard often shows the same value several times. This is because when we have aggregated values they are assigned to several regions, so the dashboard shows the value for every region.

![image](https://user-images.githubusercontent.com/56714321/116995200-0f089200-acda-11eb-9aa7-c3e34117883e.png)

I would suggest to fix that by using ALL identifier for region column in such cases or to detect when all regions are given, that it is an parameter that counts one time for all regions. What do you prefer?

**Comment by StefanieBuchholz** [comment]
This was solved, right?

**Comment by henhuy** [comment]
jey - thx for the reminder to close issue
